@tool
extends SceneTree
## Copies the published song file(s) from music/ (the authoring source — paste-
## compatible with strudel.cc) into docs/music/ (the runtime-loaded copies that
## paramo-music.js fetch()es and the web export serves). Prepends a generated-file
## banner so the copy is not hand-edited. Run before a web export.
##
##   godot --headless --path . --script res://scripts/tools/sync_music.gd
##
## Exit code 0 on success, 1 if any song failed to copy.

const SRC_DIR := "res://music/"
const DST_DIR := "res://docs/music/"

# Songs the game actually loads. Drafts / OMR scratch in music/ are NOT copied.
const PUBLISHED: Array[String] = ["ojos_azules.strudel.js"]


func _init() -> void:
	var failed := 0
	for song_name in PUBLISHED:
		if not _sync(song_name):
			failed += 1
	quit(1 if failed > 0 else 0)


func _sync(song_name: String) -> bool:
	var src := SRC_DIR + song_name
	var dst := DST_DIR + song_name
	var fr := FileAccess.open(src, FileAccess.READ)
	if fr == null:
		push_error("sync_music: cannot read %s (err %d)" % [src, FileAccess.get_open_error()])
		return false
	var body := fr.get_as_text()
	fr.close()
	var banner := (
		"// GENERATED by scripts/tools/sync_music.gd from music/%s — DO NOT EDIT.\n" % song_name
		+ "// Tune the source in music/ (paste-compatible with strudel.cc), then re-run sync.\n\n"
	)
	var fw := FileAccess.open(dst, FileAccess.WRITE)
	if fw == null:
		push_error("sync_music: cannot write %s (err %d)" % [dst, FileAccess.get_open_error()])
		return false
	fw.store_string(banner + body)
	fw.close()
	print("sync_music: %s -> %s (%d bytes)" % [src, dst, banner.length() + body.length()])
	return true
